### ISSUE TITLE
Cannot install. make: *** [auto-str] Error 1

### ISSUE THREAD

**Issue by qiqvo** [ghewgill/primegen#1]
./compile substdio.c
./compile substdi.c
./compile substdo.c
./compile subfderr.c
./compile substdio_copy.c
./makelib substdio.a substdio.o substdi.o substdo.o \
subfderr.o substdio_copy.o
./compile error.c
./compile error_str.c
./makelib error.a error.o error_str.o
./compile str_len.c
./compile byte_copy.c
./compile byte_cr.c
./makelib str.a str_len.o byte_copy.o byte_cr.o
./load auto-str substdio.a error.a str.a 
/usr/bin/ld: errno: TLS definition in /lib/x86_64-linux-gnu/libc.so.6 section .tbss mismatches non-TLS reference in substdio.a(substdo.o)
/lib/x86_64-linux-gnu/libc.so.6: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
Makefile:16: recipe for target 'auto-str' failed
make: **\* [auto-str] Error 1
al:/usr/local/primegen-0.97 $ sudo make setup
./load auto-str substdio.a error.a str.a 
/usr/bin/ld: errno: TLS definition in /lib/x86_64-linux-gnu/libc.so.6 section .tbss mismatches non-TLS reference in substdio.a(substdo.o)
/lib/x86_64-linux-gnu/libc.so.6: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
Makefile:16: recipe for target 'auto-str' failed
make: **\* [auto-str] Error 1

**Comment by qiqvo** [comment]
primegen 0.97
linux-4.4.0-34-generic-:-:-:x86_64-:-
#ifndef UINT32_H
#define UINT32_H

typedef unsigned int uint32;

#endif
#ifndef INT64_H
#define INT64_H

typedef long int64;

#endif
#ifndef UINT64_H
#define UINT64_H

typedef unsigned long uint64;

#endif
#define HASRDTSC 1

XUbuntu 16.04

**Comment by ghewgill** [comment]
This seems to be a problem with the original build, not the SCons build.
